-- ============================================================
-- 业务表 · 建在 cs_v1 库（智能体执行 SQL 的目标库）
--
--   这是智能体**查询 / 修改 / 删除**的数据。
--   执行一律走受限角色 agent_sql_runner：
--     ✅ SELECT / INSERT / UPDATE / DELETE
--     🚫 DROP / TRUNCATE / ALTER / CREATE / GRANT … 全都没有权限
-- ============================================================

CREATE TABLE IF NOT EXISTS customers (
    id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       TEXT        NOT NULL,
    phone      TEXT,
    city       TEXT        NOT NULL,
    level      TEXT        NOT NULL DEFAULT '普通',     -- 普通 / 银牌 / 金牌
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS products (
    id       INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name     TEXT           NOT NULL,
    category TEXT           NOT NULL,
    price    NUMERIC(10, 2) NOT NULL,
    stock    INT            NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS orders (
    id           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id  INT            NOT NULL REFERENCES customers(id),
    status       TEXT           NOT NULL DEFAULT '待付款',  -- 待付款/已付款/已发货/已完成/已取消
    total_amount NUMERIC(12, 2) NOT NULL DEFAULT 0,
    created_at   TIMESTAMPTZ    NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS order_items (
    id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id   INT            NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    product_id INT            NOT NULL REFERENCES products(id),
    qty        INT            NOT NULL,
    unit_price NUMERIC(10, 2) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_orders_customer ON orders(customer_id);
CREATE INDEX IF NOT EXISTS idx_orders_status   ON orders(status);
CREATE INDEX IF NOT EXISTS idx_items_order     ON order_items(order_id);

-- 受限角色：**只有这 4 张表的 DML**
GRANT USAGE ON SCHEMA public TO agent_sql_runner;
GRANT SELECT, INSERT, UPDATE, DELETE
   ON customers, products, orders, order_items TO agent_sql_runner;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO agent_sql_runner;
